version: "3.9"

services:
  app:
    build: .
    container_name: skygate_app
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - JWT_SECRET=skygate__
      - SALT_ROUND=8
      - MONGODB_URL=mongodb://mongo:27017/skygate_db
    depends_on:
      - mongo
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  mongo:
    image: mongo:7
    container_name: skygate_mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: skygate_db
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
